apiVersion: skaffold/v1alpha2
kind: Config
build:
  tagPolicy:
    envTemplate:
      template: "{{.DOCKER_REGISTRY}}/{{.ORG}}/{{.APP_NAME}}:{{.VERSION}}"
  artifacts:
  - imageName: changeme
    workspace: .
    docker:
      buildArgs:
        GIT_SHA: "{{.GIT_COMMIT}}"
        WORKFLOW_RELEASE: "{{.VERSION}}"
  local: {}
deploy:
  helm:
    releases:
    - name: "{{.APP_NAME}}"
      chartPath: "charts/croc-hunter-jenkinsx"
      setValueTemplates:
        image.repository: "{{.DOCKER_REGISTRY}}/{{.ORG}}/{{.APP_NAME}}"
        image.tag: "{{.VERSION}}"
