apiVersion: skaffold/v1alpha2
kind: Config
build:
  tagPolicy:
    envTemplate:
      template: "docker-registry.jx.aks-01.az.estrado.io:443/{{.ORG}}/{{.APP_NAME}}:{{.VERSION}}"
  artifacts:
  - imageName: changeme
    workspace: .
    docker:
      buildArgs:
        GIT_SHA: "{{.GIT_COMMIT}}"
        WORKFLOW_RELEASE: "{{.VERSION}}"
  local: {}
deploy:
  kubectl:
    manifests:
